version: '3'
services:
    db:
        image: mongo:latest
    backend:
        image: node:latest
        volumes:
            - ./backend:/backend
        ports:
            - 3000:3000
        command: bash -c "cd /backend && npm install && node app"
    frontend:
        image: nginx:latest
        volumes:
            - ./frontend:/usr/share/nginx/html
        ports:
            - 8080:80
